name: 'Configuration Update Base'
type: module
description: 'Provides basic revert and update functionality for other modules.'
core_version_requirement: ^9.4 || ^10
php: 8.1
dependencies:
  - drupal:config
